services:
  backend:
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      DDL_MODE: ${DDL_MODE}
  postgres:
    ports:
      - "5432:5432"
  pgadmin:
    ports:
      - "15432:15432"
