spring:
  config:
    import: optional:file:../.env[.properties]

  datasource:
    name: ${POSTGRES_DB:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver

  jackson:
    time-zone: ${TZ:UTC}

  jpa:
    hibernate:
      ddl-auto: ${DDL_MODE:none}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  web:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: ${ALLOWED_METHODS:GET, POST, PUT, DELETE}
      allowed-headers: "*"
      allow-credentials: true

logging:
  level:
    com.proffen: INFO
    org.springframework: INFO
security:
  jwt:
    secret: ${JWT_SECRET}
    access: ${JWT_ACCESS_TTL}
    refresh: ${JWT_REFRESH_TTL}

