spring:
  config:
    import: optional:file:../.env[.properties]
  datasource:
    name: ${POSTGRES_DB:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  jackson:
    time-zone: ${TZ}
  jpa:
    hibernate:
      ddl-auto: ${DDL_MODE:none}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
logging:
  level:
    com.proffen: INFO
    org.springframework: INFO
security:
  jwt:
    secret: ${JWT_SECRET}
    access: ${JWT_ACCESS_TTL}
    refresh: ${JWT_REFRESH_TTL}